export default {
  // Auth
  SPLASH: 'SPLASH',
  LOGIN: 'LOGIN',
  REGISTER: 'REGISTER',

  //Home
  HOME: 'HOME',
  ADD_DRIVER: 'ADD_DRIVER',
  ALL_DRIVER: 'ALL_DRIVER',
  DRIVER_DETAILS: 'DRIVER_DETAILS',
  PAGINATION: 'PAGINATION',
};
